[package]
name = "translators"
version = "0.1.0"
authors = ["Evan Brass <brassev@oregonstate.edu>"]
edition = "2018"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.17.0"
logos-derive = "0.9.7"

[dependencies]
logos = "0.9.7"
lalrpop-util = "0.17.0"
regex = "0.2.1"